### ISSUE TITLE
passing autoPlay 'true' crashes the app

### ISSUE THREAD

**Issue by rafwit** [div-Leo/gallereact#31]
Hey Leo, great job with the package, very cool. I found it really useful for my project!

Here is one thing that I found not working.
Attempt to use `autoPlay={true}` crashes the app with `ReferenceError: goToNextSlide is not defined`. 

Steps to reproduce:

1. pass `autoPlay={true}` to your instance of `Gallereact`

Tested both on my app, as well as on the example provided in the /examples directory. It looks like it gets triggered in `src/Gallereact.js line 28` but I'm not sure.

**Comment by Suroor-Ahmmad** [comment]
Did you fix it?

**Comment by rafwit** [comment]
well, not, but did a dirty workaround

```javascript
const Slider = () => {
  const [index, setIndex] = useState(0);

  useEffect(() => {
    const timeoutId = setTimeout(() => {
      if (index < IMAGES_FOR_SLIDER.length - 1) {
        setIndex(index + 1);
      } else {
        setIndex(0);
      }
    }, 4000);
    return () => clearTimeout(timeoutId);
  }, [index]);

  return (<Gallereact inputIndex={index} />);
}
```

**Comment by div-Leo** [comment]
Hey @rafwit! 
Sorry, it has been a while that I didn't check the project 😅 
I must have missed it during the last refactor, this is why I should have had tests...

Feel free to make a PR if you want otherwise I'll try to fix it in the next weeks, at the latest during the Xmax holidays!
Thank you so much for the comment, hope you're doing great!

**Comment by rafwit** [comment]
Hey, @div-Leo! all good, enjoying the dev life a lot 🌈🚀
Hope all is good on your end too!

I opened PR #36 🎁 with my proposition of the fix and a little adjustment of the contribution guide to (I hope) make it easier for others to contribute.

All the best to you!
